auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:year:month:day/:title

title: gejiaheng.com
url: http://gejiaheng.github.io
feed: /atom.xml
author_info: <a href="http://gejiaheng.github.io">GeJiaheng</a>
