# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            GeJiaheng
description:      'I am an Android engineer, now working in Zhihu.'
url:              gejiaheng.github.io
baseurl:          /
logo:             /content/images/me.png

author:
  name:           'GeJiaheng'
  url:            https://plus.google.com/+JiahengGe

paginate:         5

disqus_shortname: gejiaheng

github:
  repo:           https://github.com/gejiaheng/gejiaheng.github.io

gems:             [jekyll-paginate, jekyll-gist, jekyll-sitemap]


twitter: '@GeJiaheng'

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
