# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Jiaheng Ge
title: Android Developer
email: gejiaheng@gmail.com
website: jiaheng.me

# Social links
twitter_username: gejiaheng
github_username:  gejiaheng
linkedin_username: gejiaheng
medium_user: gejiaheng
zhihu_username: bitrandom
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/avatar.png
about_content: | 
  Hi, my name is Jiaheng Ge, I'm an <mark>Android developer</mark> with over 5 years experience. I'm passionate about creating smooth and reliable user experience for Android apps.
  I focused on mobile engineering productivity and app infrastructure in the last job experience as Android infrastructure team's tech lead.

  Aside from mobile development, I spend a lot of time expanding my technical horizons in fields including <mark>AI</mark> and <mark>IoT</mark>. 
  I'm excited about making technology accessible and empowering engineers to solve valuable problems for people.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# educaton_title: Education #(Use this to override about education section title)

# More Section
more_title: When I'm Not Programming
more_content: |
  I love watching all kinds of movies. My favourite movie star is Christain Bale. I've dreamed about becoming a film director. 
  But unfortunately, I don't have Ang Lee's talent. 

  Also, I love travelling and experiencing diffrent cultures. I've been to USA, Japan, Thailand and Australia. Not a lot of places, hum? Probably.
  That's why my other big dream is to travel around the world.

  "I wanted to live deep and suck out all the marrow of life."

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
